/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dxw.server.ui;

import com.dxw.flfs.communication.PlcProxy;
import com.dxw.flfs.communication.PlcProxyImpl;

/**
 *
 * @author Administrator
 */
public class HoldingRegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form HoldingRegisterPanel
     */
    public HoldingRegisterPanel() {
        initComponents();
        
        this.buttonGroup1.add(this.radioReadFloat);
        this.buttonGroup1.add(this.radioReadInt);
        this.buttonGroup1.add(this.radioReadShort);
        
        this.buttonGroup2.add(this.radioWriteFloat);
        this.buttonGroup2.add(this.radioWriteInt);
        this.buttonGroup2.add(this.radioWriteShort);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtReadOffset = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        radioReadShort = new javax.swing.JRadioButton();
        radioReadInt = new javax.swing.JRadioButton();
        radioReadFloat = new javax.swing.JRadioButton();
        btnRead = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtReadResult = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtReadOffset1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnWrite = new javax.swing.JButton();
        txtValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        radioWriteShort = new javax.swing.JRadioButton();
        radioWriteInt = new javax.swing.JRadioButton();
        radioWriteFloat = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Offset");
        jLabel2.setToolTipText("");

        jLabel3.setText("Type");

        radioReadShort.setSelected(true);
        radioReadShort.setText("short");

        radioReadInt.setText("int");

        radioReadFloat.setText("float");

        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReadOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioReadFloat)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioReadInt)
                            .addComponent(radioReadShort))
                        .addGap(28, 28, 28)
                        .addComponent(btnRead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addComponent(txtReadResult, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtReadOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(radioReadShort))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioReadInt))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRead)
                        .addComponent(jLabel6)
                        .addComponent(txtReadResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioReadFloat)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Read", jPanel6);

        jLabel4.setText("Offset");
        jLabel4.setToolTipText("");

        jLabel5.setText("Type");

        btnWrite.setText("Write");
        btnWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteActionPerformed(evt);
            }
        });

        jLabel1.setText("Value");

        radioWriteShort.setSelected(true);
        radioWriteShort.setText("short");

        radioWriteInt.setText("int");

        radioWriteFloat.setText("float");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValue, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(txtReadOffset1))
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioWriteFloat)
                    .addComponent(radioWriteInt)
                    .addComponent(radioWriteShort))
                .addGap(28, 28, 28)
                .addComponent(btnWrite)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(radioWriteShort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioWriteInt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioWriteFloat))
                    .addComponent(btnWrite)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtReadOffset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(43, 43, 43))
        );

        jTabbedPane2.addTab("Write", jPanel7);

        add(jTabbedPane2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        PlcProxy proxy = PlcProxyImpl.getInstance();

        int offset = Integer.parseInt(this.txtReadOffset.getText());

        if (this.radioReadShort.isSelected()) {
            short s = proxy.getRegisterShort(offset, 1);
            this.txtReadResult.setText(String.format("%d", s));

        } else if (this.radioReadInt.isSelected()) {
            int x = proxy.getRegisterInt(offset, 1);
            this.txtReadResult.setText(String.format("%d", x));
        }
        else if (this.radioReadFloat.isSelected()) {
            float v = proxy.getRegisterFloat(offset, 1);
            this.txtReadResult.setText(String.format("%f", v));
        }

    }//GEN-LAST:event_btnReadActionPerformed

    private void btnWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteActionPerformed
        PlcProxy proxy = PlcProxyImpl.getInstance();

        int offset = Integer.parseInt(this.txtReadOffset.getText());
        
        if (this.radioReadShort.isSelected()) {
            short value = Short.parseShort(this.txtValue.getText());
            proxy.setRegister(offset, value);
            

        } else if (this.radioReadInt.isSelected()) {
            int value = Integer.parseInt(this.txtValue.getText());
            proxy.setRegister(offset, value);
        }
        else if (this.radioReadFloat.isSelected()) {
            float value = Float.parseFloat(this.txtValue.getText());
            proxy.setRegister(offset, value);
        }
    }//GEN-LAST:event_btnWriteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnWrite;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane2;
    javax.swing.JRadioButton radioReadFloat;
    javax.swing.JRadioButton radioReadInt;
    javax.swing.JRadioButton radioReadShort;
    javax.swing.JRadioButton radioWriteFloat;
    javax.swing.JRadioButton radioWriteInt;
    javax.swing.JRadioButton radioWriteShort;
    javax.swing.JTextField txtReadOffset;
    javax.swing.JTextField txtReadOffset1;
    private javax.swing.JTextField txtReadResult;
    javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
