/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dxw.server.ui;


import com.dxw.common.ms.Notification;
import com.dxw.common.ms.NotificationManager;
import com.dxw.common.services.ServiceRegistry;
import com.dxw.common.services.ServiceRegistryImpl;
import com.dxw.common.services.Services;
import com.dxw.flfs.communication.PlcProxy;
import com.dxw.flfs.communication.PlcProxyImpl;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author pronics3
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        init();
        
        
    }
    NotificationManager notificationManager;
    private void init() {
        ServiceRegistry registry = ServiceRegistryImpl.getInstance();
        
        notificationManager = (NotificationManager)registry.lookupService( Services.NOTIFICATION_MANAGER);
        
        notificationManager.addReceiver((String tag, Notification notification) -> {
            String message = String.format("[%S] %s %s\r\n", tag, 
                    new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(notification.getWhen())),
                    notification.getContent().toString());
            txtMessage.append(message);
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        javax.swing.JPanel panelUpper = new javax.swing.JPanel();
        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JPanel panelCoil = new javax.swing.JPanel();
        com.dxw.server.ui.CoilPanel coilPanel1 = new com.dxw.server.ui.CoilPanel();
        javax.swing.JPanel panelDiscreteInput = new javax.swing.JPanel();
        com.dxw.server.ui.DesceteInputPanel desceteInputPanel1 = new com.dxw.server.ui.DesceteInputPanel();
        javax.swing.JPanel panelHoldingRegister = new javax.swing.JPanel();
        com.dxw.server.ui.HoldingRegisterPanel holdingRegisterPanel1 = new com.dxw.server.ui.HoldingRegisterPanel();
        javax.swing.JPanel panelInputRegister = new javax.swing.JPanel();
        com.dxw.server.ui.InputRegisterPanel inputRegisterPanel1 = new com.dxw.server.ui.InputRegisterPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modbus模拟器");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.4);

        panelUpper.setLayout(new java.awt.BorderLayout());

        panelCoil.setLayout(new java.awt.BorderLayout());
        panelCoil.add(coilPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Coil", panelCoil);

        panelDiscreteInput.add(desceteInputPanel1);

        jTabbedPane1.addTab("Discrete Input", panelDiscreteInput);

        panelHoldingRegister.setLayout(new java.awt.BorderLayout());
        panelHoldingRegister.add(holdingRegisterPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Holding Register", panelHoldingRegister);

        panelInputRegister.add(inputRegisterPanel1);

        jTabbedPane1.addTab("Input Register", panelInputRegister);

        panelUpper.add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setTopComponent(panelUpper);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtMessage.setBackground(new java.awt.Color(51, 51, 51));
        txtMessage.setColumns(20);
        txtMessage.setForeground(new java.awt.Color(255, 255, 255));
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        jPanel1.add(jScrollPane1);

        jSplitPane1.setRightComponent(jPanel1);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.ButtonGroup buttonGroup1;
    javax.swing.JTextArea txtMessage;
    // End of variables declaration//GEN-END:variables
}
